demo:
	python2.7 greedySearch_nStop.py ../../Graphs/chocMediaWiki.sentenceEdges.graph ../../models/unified/chocmediawiki/unified_orderedALL_CHOC.txt > output_greedy_TOP20_CHOC_fast_copy.txt &
	python2.7 greedySearch_nStop.py ../../Graphs/dstarMediaWiki.sentenceEdges.graph ../../models/unified/dstarmediawiki/unified_orderedALL_DSTAR.txt > output_greedy_TOP20_DSTAR_fast_copy.txt &
	python2.7 greedySearch_nStop.py ../../Graphs/kievMediaWiki.sentenceEdges.graph ../../models/unified/kievmediawiki/unified_orderedALL_KIEV.txt > output_greedy_TOP20_KIEV_fast_copy.txt &
	python2.7 greedySearch_nStop.py ../../Graphs/lcrMediaWiki.sentenceEdges.graph ../../models/unified/lcrmediawiki/unified_orderedALL_LCR.txt > output_greedy_TOP20_LCR_fast_copy.txt &
